-- PRODUCTION SERVER 10.20.10.14:5432
-- root Q9A9YcE6XHgBbRZR

CREATE ROLE "PattynAdmin" WITH 
	SUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	PASSWORD 'prod_z5GKS=rnk5#@vUs+gUGc';

